import { Assessment, Question, User } from '../types';

export const ASSESSMENT_CATEGORIES = [
  'Software Engineering',
  'Frontend Development',
  'Backend & Databases',
  'Data Science & AI',
  'DevOps & Cloud',
  'Cybersecurity',
  'Product Management',
  'General Aptitude',
  'Language & Communication',
] as const;

export const DEMO_USERS: User[] = [
  {
    id: 'user-admin-1',
    name: 'Sarah Connor',
    email: 'admin@assesspulse.io',
    role: 'ADMIN',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    organization: 'Apex Tech Academy',
    createdAt: '2024-01-15T08:00:00.000Z',
  },
  {
    id: 'user-creator-1',
    name: 'Alex Rivera',
    email: 'creator@assesspulse.io',
    role: 'TEST_CREATOR',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    organization: 'CyberCore Systems',
    createdAt: '2024-02-10T10:30:00.000Z',
  },
  {
    id: 'user-participant-1',
    name: 'Jordan Lee',
    email: 'jordan.lee@example.com',
    role: 'PARTICIPANT',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    organization: 'MIT Open Courseware',
    createdAt: '2024-03-01T14:00:00.000Z',
  },
];

export const INITIAL_ASSESSMENTS: Assessment[] = [
  {
    id: 'test-fe-mastery',
    title: 'Frontend React & Modern Web Mastery',
    description: 'Comprehensive evaluation covering React 18, State Architecture, Web Performance, and Async Networking.',
    category: 'Frontend Development',
    instructions: '1. Total of 5 questions.\n2. Ensure stable internet connection.\n3. Do not switch tabs or minimize the test window.\n4. Passing score is 70%.',
    accessCode: 'REACT99',
    creatorId: 'user-admin-1',
    creatorName: 'Sarah Connor',
    status: 'ACTIVE',
    questionsCount: 5,
    totalMarks: 25,
    settings: {
      shuffleQuestions: false,
      shuffleOptions: true,
      showImmediateResults: true,
      allowAnswerReview: true,
      maxAttempts: 2,
      timeLimitMinutes: 15,
      passingScorePercentage: 70,
      requireParticipantEmail: true,
      requireParticipantId: true,
      enableAntiCheatWarnings: true,
    },
    createdAt: '2024-04-01T09:00:00.000Z',
    updatedAt: '2024-04-10T11:20:00.000Z',
  },
  {
    id: 'test-cloud-devops',
    title: 'Cloud Architecture & DevOps Essentials',
    description: 'Assess fundamental principles of CI/CD pipelines, Docker containers, Kubernetes orchestrations, and Microservices.',
    category: 'DevOps & Cloud',
    instructions: 'Timed assessment. All single & multi-choice questions carry weighted scoring.',
    accessCode: 'CLOUD44',
    creatorId: 'user-admin-1',
    creatorName: 'Sarah Connor',
    status: 'ACTIVE',
    questionsCount: 4,
    totalMarks: 20,
    settings: {
      shuffleQuestions: true,
      shuffleOptions: true,
      showImmediateResults: true,
      allowAnswerReview: true,
      maxAttempts: 1,
      timeLimitMinutes: 20,
      passingScorePercentage: 65,
      requireParticipantEmail: true,
      requireParticipantId: false,
      enableAntiCheatWarnings: true,
    },
    createdAt: '2024-04-05T14:30:00.000Z',
    updatedAt: '2024-04-12T16:45:00.000Z',
  },
  {
    id: 'test-sql-db',
    title: 'PostgreSQL & Database Systems Design',
    description: 'Relational schema normalization, indexing strategies, ACID compliance, and query optimization.',
    category: 'Backend & Databases',
    instructions: 'Read each question carefully. Some questions require written reasoning.',
    accessCode: 'SQL2024',
    creatorId: 'user-creator-1',
    creatorName: 'Alex Rivera',
    status: 'DRAFT',
    questionsCount: 3,
    totalMarks: 15,
    settings: {
      shuffleQuestions: false,
      shuffleOptions: false,
      showImmediateResults: false,
      allowAnswerReview: false,
      maxAttempts: 1,
      timeLimitMinutes: 25,
      passingScorePercentage: 75,
      requireParticipantEmail: true,
      requireParticipantId: true,
      enableAntiCheatWarnings: true,
    },
    createdAt: '2024-04-15T10:00:00.000Z',
    updatedAt: '2024-04-15T10:00:00.000Z',
  },
];

export const INITIAL_QUESTIONS: Record<string, Question[]> = {
  'test-fe-mastery': [
    {
      id: 'q-fe-1',
      assessmentId: 'test-fe-mastery',
      text: 'What is the primary function of the React Virtual DOM?',
      type: 'SINGLE_CHOICE',
      marks: 5,
      order: 1,
      isRequired: true,
      explanation: 'The Virtual DOM minimizes expensive direct DOM manipulations by diffing changes in memory and batching real DOM updates.',
      options: [
        { id: 'opt-1', text: 'To directly manipulate the browser HTML without JavaScript engine' },
        { id: 'opt-2', text: 'To perform fast in-memory diffing and batch actual browser DOM updates', isCorrect: true },
        { id: 'opt-3', text: 'To act as a persistent database store inside client browser' },
        { id: 'opt-4', text: 'To replace CSS stylesheets with binary stylesheets' },
      ],
      correctAnswers: ['opt-2'],
    },
    {
      id: 'q-fe-2',
      assessmentId: 'test-fe-mastery',
      text: 'Which of the following React Hooks cause re-renders when their state changes? (Select all that apply)',
      type: 'MULTIPLE_CHOICE',
      marks: 5,
      order: 2,
      isRequired: true,
      explanation: 'useState and useReducer trigger re-renders upon state updates. useRef preserves values across renders without causing a re-render.',
      options: [
        { id: 'opt-21', text: 'useState', isCorrect: true },
        { id: 'opt-22', text: 'useRef' },
        { id: 'opt-23', text: 'useReducer', isCorrect: true },
        { id: 'opt-24', text: 'useMemo' },
      ],
      correctAnswers: ['opt-21', 'opt-23'],
    },
    {
      id: 'q-fe-3',
      assessmentId: 'test-fe-mastery',
      text: 'True or False: React component state updates via setter functions are guaranteed to be executed synchronously on the exact line called.',
      type: 'TRUE_FALSE',
      marks: 5,
      order: 3,
      isRequired: true,
      explanation: 'False. React state updates are batched and scheduled asynchronously for performance optimization.',
      options: [
        { id: 'opt-tf-1', text: 'True' },
        { id: 'opt-tf-2', text: 'False', isCorrect: true },
      ],
      correctAnswers: ['opt-tf-2'],
    },
    {
      id: 'q-fe-4',
      assessmentId: 'test-fe-mastery',
      text: 'Explain the difference between useEffect and useLayoutEffect in 1-2 concise sentences.',
      type: 'SHORT_ANSWER',
      marks: 5,
      order: 4,
      isRequired: true,
      explanation: 'useLayoutEffect runs synchronously immediately after DOM mutations before browser paint, whereas useEffect runs asynchronously after browser paint.',
      correctAnswers: ['DOM mutation', 'paint', 'synchronous'],
    },
    {
      id: 'q-fe-5',
      assessmentId: 'test-fe-mastery',
      text: 'Describe how you would optimize a React application that is experiencing slow rendering when displaying a list of 10,000 items.',
      type: 'LONG_ANSWER',
      marks: 5,
      order: 5,
      isRequired: false,
      explanation: 'Key strategies include: windowing/virtualization (e.g. react-window), pagination, memoizing items with React.memo, avoiding anonymous inline handler functions, and server-side filtering.',
      correctAnswers: [],
    },
  ],
  'test-cloud-devops': [
    {
      id: 'q-cd-1',
      assessmentId: 'test-cloud-devops',
      text: 'In Kubernetes, what is the smallest deployable compute unit?',
      type: 'SINGLE_CHOICE',
      marks: 5,
      order: 1,
      isRequired: true,
      explanation: 'A Pod is the smallest execution unit in Kubernetes encapsulating one or more containers.',
      options: [
        { id: 'cd-opt-1', text: 'Container' },
        { id: 'cd-opt-2', text: 'Pod', isCorrect: true },
        { id: 'cd-opt-3', text: 'ReplicaSet' },
        { id: 'cd-opt-4', text: 'Cluster' },
      ],
      correctAnswers: ['cd-opt-2'],
    },
    {
      id: 'q-cd-2',
      assessmentId: 'test-cloud-devops',
      text: 'Which HTTP status code signifies that a client must authenticate itself to get the requested response?',
      type: 'SINGLE_CHOICE',
      marks: 5,
      order: 2,
      isRequired: true,
      explanation: 'HTTP 401 Unauthorized indicates unauthenticated access.',
      options: [
        { id: 'cd-opt-21', text: '400 Bad Request' },
        { id: 'cd-opt-22', text: '401 Unauthorized', isCorrect: true },
        { id: 'cd-opt-23', text: '403 Forbidden' },
        { id: 'cd-opt-24', text: '404 Not Found' },
      ],
      correctAnswers: ['cd-opt-22'],
    },
    {
      id: 'q-cd-3',
      assessmentId: 'test-cloud-devops',
      text: 'True or False: Docker images are composed of read-only immutable layers.',
      type: 'TRUE_FALSE',
      marks: 5,
      order: 3,
      isRequired: true,
      explanation: 'True. Docker images consist of read-only layers with a writable top layer added during container execution.',
      options: [
        { id: 'cd-tf-1', text: 'True', isCorrect: true },
        { id: 'cd-tf-2', text: 'False' },
      ],
      correctAnswers: ['cd-tf-1'],
    },
    {
      id: 'q-cd-4',
      assessmentId: 'test-cloud-devops',
      text: 'What CI/CD stage comes immediately after code integration and automated test execution?',
      type: 'SINGLE_CHOICE',
      marks: 5,
      order: 4,
      isRequired: true,
      explanation: 'Artifact creation / container image build and deployment staging.',
      options: [
        { id: 'cd-opt-41', text: 'Continuous Deployment / Delivery Build', isCorrect: true },
        { id: 'cd-opt-42', text: 'Git Commit Writing' },
        { id: 'cd-opt-43', text: 'Database Decommissioning' },
        { id: 'cd-opt-44', text: 'Code Repository Deletion' },
      ],
      correctAnswers: ['cd-opt-41'],
    },
  ],
};
